name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: asia-southeast1
  SERVICE: dooform-placeholder-model
  REGION: asia-southeast1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud as credential helper
      run: |
        gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$SERVICE/$SERVICE:$GITHUB_SHA .
        docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$SERVICE/$SERVICE:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        cat > env-vars.yaml << EOF
        SERVER_PORT: "8081"
        ENVIRONMENT: "production"
        BASE_URL: "${{ secrets.BASE_URL }}"
        ALLOW_ORIGINS: "${{ secrets.ALLOW_ORIGINS }}"
        DB_HOST: "/cloudsql/${{ secrets.CLOUD_SQL_CONNECTION_NAME }}"
        DB_USER: "${{ secrets.DB_USER }}"
        DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
        DB_NAME: "${{ secrets.DB_NAME }}"
        GCS_BUCKET_NAME: "${{ secrets.GCS_BUCKET_NAME }}"
        GOOGLE_CLOUD_PROJECT: "${{ secrets.GCP_PROJECT_ID }}"
        GOTENBERG_URL: "${{ secrets.GOTENBERG_URL }}"
        GOTENBERG_TIMEOUT: "30s"
        EOF

        gcloud run deploy $SERVICE \
          --image $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$SERVICE/$SERVICE:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port=8081 \
          --memory=512Mi \
          --cpu=1 \
          --timeout=300 \
          --max-instances=2 \
          --min-instances=0 \
          --concurrency=80 \
          --service-account=${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }} \
          --env-vars-file=env-vars.yaml \
          --verbosity=debug
